name: Create Tag on PR Merge

on:
  push:
    branches:
      - main

env:
  HEADERS: "-H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28'"

jobs:
  create_tag_on_merge:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[V') && contains(github.event.head_commit.message, ']')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if commit message matches the pattern
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          echo "Full commit message: $commit_message"

          # Extract the first line (commit title) from the full commit message
          commit_title=$(echo "$commit_message" | head -n 1)
          echo "Commit title: $commit_title"

          # Use grep to find lines that match the pattern [Vx.x.x]
          filtered_message=$(echo "$commit_title" | grep -o '\[V[0-9]*\.[0-9]*\.[0-9]*\]' | tr -d '[]')

          if [ -n "$filtered_message" ]; then
            echo "Commit message matches the pattern.."
            echo "Tag name: $filtered_message"

            # save $filtered_message to $TAG_NAME
            echo "TAG_NAME=$filtered_message" >> $GITHUB_ENV

          else
            echo "Commit message does not match the pattern."
            exit 1
          fi

      - name: Create Tag
        run: |
          tag_name="${{ env.TAG_NAME }}"
          git tag "${tag_name}" "${GITHUB_SHA}"

      - name: Push Tag to Origin
        if: env.TAG_NAME != ''
        run: |
          # git push origin "${{ env.TAG_NAME }}"

      - name: Get changes from CHANGELOG.md
        id: get_changelog_changes
        run: |
          # Fetch the latest commit from the main branch
          git fetch origin main

          # Get the content of the CHANGELOG.md file from the main branch
          changelog_content=$(git show origin/main:CHANGELOG.md)

          # Use awk to extract the content between the first and second "##" lines
          recent_changelog_update=$(echo "$changelog_content" | awk '/^## / && !found {found = 1; print; next} found && /^## / {exit} found {print}')

          echo "Recent changes from CHANGELOG.md:"
          echo "$recent_changelog_update"
