name: Create Tag on PR Merge
on:
  pull_request:
    types:
      - closed

jobs:
  create_tag_on_merge:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.title, '[V') &&
      endsWith(github.event.pull_request.title, ']')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract PR title and branch
        id: get_pr_details
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "TAG_NAME=${title//[\[\]]/}" >> $GITHUB_ENV
          echo "PR_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Create Tag
        id: create_tag
        run: |
          tag_name="${{ env.TAG_NAME }}"
          git tag "${tag_name}" "${GITHUB_SHA}"

      - name: Push Tag to Origin
        if: env.TAG_NAME != ''
        run: |
          git push origin "${{ env.TAG_NAME }}"

      - name: Get Changelog Changes
        id: get_changelog_changes
        run: |
          # Fetch PR changes in the `CHANGELOG.md` file

          # echo repository_owner
          echo ${{ github.repository_owner }}

          # echo repository_name
          echo ${{ github.event.repository.name }}

          changelog_changes=$(curl -s "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/compare/main...${{ env.PR_BRANCH }}" | jq '.files | map(select(.filename == "CHANGELOG.md")) | .[0].patch')
          echo "CHANGELOG_CHANGES=${changelog_changes}" >> $GITHUB_ENV
