name: Lock New Branch new

on:
  push:
    branches:
      - main

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lock New Branch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const branch = "main";
            const { data: branchData } = await github.repos.getBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: branch,
            });

            if (!branchData.protected) {
              await github.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch,
                required_status_checks: null,
                enforce_admins: true,
                required_pull_request_reviews: null,
                restrictions: null,
              });
              console.log(`The ${branch} branchd is now locked.`);
            } else {
              console.log(`The ${branch} branch is already locked.`);
            }
