name: Lock Main Branch new

on:
  push:
    branches:
      - main

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: Lock Main Branch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = "main";
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch,
              base: branch,
              title: `Lock ${branch} branch`,
              body: `This pull request is used to lock the ${branch} branch.`,
              maintainer_can_modify: true,
            });
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequest.number,
            });
            if (reviews.length === 0) {
              await github.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequest.number,
                reviewers: [context.repo.owner],
              });
            }
