name: Lock Main Branch new
on:
  push:
    branches:
      - main

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lock Main Branch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = "main"; // Update to "main" since your branch is called "main"
            const { data: branchData } = await github.repos.getBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: branch,
            });

            // Check if branch protection exists, if not, create it
            if (!branchData.protected) {
              await github.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch,
                required_status_checks: null,
                enforce_admins: true,
                required_pull_request_reviews: null,
                restrictions: null,
              });
              console.log(`The ${branch} branch is now locked.`);
            } else {
              console.log(`The ${branch} branch is already locked.`);
            }
