name: Playwright Tests

on: [deployment_status, pull_request]

jobs:
  e2e-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    if: ${{ github.event_name == 'pull_request' && startsWith(github.head_ref, 'v') }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: test
        run: |
          echo 'print github.head_ref: "${{ github.head_ref }}"'  

          if ! .github/scripts/is-valid-tag.sh "${{ github.head_ref }}"; then
            echo "Invalid tag: ${{ github.head_ref }}"
            exit 1
          else
            echo "Valid tag: ${{ github.head_ref }}"
          fi
  
      - name: Install dependencies..
        run: yarn add @playwright/test

      - name: Install Playwright Browsers
        run: npx playwright install chromium
