name: Playwright Tests

on:
  deployment_status:

  pull_request:
    types:
      - opened

jobs:
  e2e-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    if: |
      (
        github.event.deployment_status.state == 'success' &&
        contains(github.event.deployment.environment, 'jampack-landing-pr')
      ) || (
        github.event_name == 'pull_request' &&
        source ./.github/scripts/functions.sh && is_valid_tag "${{ github.head_ref }}"
      )

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies......
        run: yarn add @playwright/test
