name: Create Pull Request with User-Specified Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the bump (e.g., "1.2.3")'
        required: true

jobs:
  version_bump_and_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Ensure Node.js and Yarn are installed
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust the Node.js version as needed
          registry-url: "https://registry.npmjs.org/" # Required for Yarn

      # Read the existing 'package.json' file and extract the current version
      - name: Get values from the package.json
        id: packageJson
        uses: RadovanPelka/github-action-json@main
        with:
          path: "package.json" # default value

      - run: echo "name - ${{ steps.packageJson.outputs.name }}"
      - run: echo "version - ${{ steps.packageJson.outputs.version }}"
      - run: echo "author - ${{ steps.packageJson.outputs.author }}"

      # Update the version in 'package.json'
      - name: Set and Get values from the package.json
        id: packageJson
        uses: RadovanPelka/github-action-json@main
        with:
          path: "package.json" # default value
          replaceWith: |
            {
              "engines": { "node": "16" }
              "version": 10
            }

      - run: echo "version - ${{ steps.packageJson.outputs.version }}"
      - run: echo "engines - ${{ steps.packageJson.outputs.engines }}"

      # # Set the user-specified version in the 'package.json' file
      # - name: Set Version in package.json
      #   run: |
      #     echo "{\"version\": \"$INPUT_VERSION\"}" > package.json

      # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: version-bump # Replace this with the branch where you want to create the PR
          title: "Version Bump to ${{ inputs.version }}"
          body: "Automated version bump to ${{ inputs.version }}"
