name: Create Pull Request with User-Specified Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the bump (e.g., "1.2.3")'
        required: true

jobs:
  version_bump_and_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure Node.js and Yarn are installed
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust the Node.js version as needed
          registry-url: "https://registry.npmjs.org/" # Required for Yarn

      # Read the existing 'package.json' file
      - name: Read Package JSON
        id: read_package_json
        run: |
          echo "::set-output name=content::$(cat package.json)"

      # Update the version in 'package.json'
      - name: Update Package JSON
        id: update_package_json
        run: |
          echo "${{ steps.read_package_json.outputs.content }}" | jq '.version = $VERSION' --arg VERSION "${{ inputs.version }}" > package.json

      # # Set the user-specified version in the 'package.json' file
      # - name: Set Version in package.json
      #   run: |
      #     echo "{\"version\": \"$INPUT_VERSION\"}" > package.json

      # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: version-bump # Replace this with the branch where you want to create the PR
          title: "Version Bump to ${{ inputs.version }}"
          body: "Automated version bump to ${{ inputs.version }}"
