name: Version Bump PR

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Git user name and email from the secrets
      - name: Configure Git
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      # Ensure Node.js and Yarn are installed
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies and bump the version using 'yarn version'
      - name: Bump version in package.json
        run: |
          yarn install
          # Choose the appropriate version bump option (major, minor, or patch)
          yarn version --patch # For a patch version bump

      - name: Commit changes
        run: |
          git commit -am "Bump version in package.json"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: version-bump
          title: "Version Bump: ${{ steps.bump.outputs.new_version }}"
          body: "Automated version bump to ${{ steps.bump.outputs.new_version }}"
